### ISSUE TITLE
[BUG] <Registration under Admin>

### ISSUE THREAD

**Issue by AbiAthmakuri034** [deltasig/sphinx#81]
**Describe the bug**
I am trying to register the new members and I was getting an Authentication Token already in use error at the top of the webpage in red. They have not received emails for a password reset. When I try to unregister them, I get a sign in prompt then followed by an error 500. 

**To Reproduce**
1. Click Admin and then Registration
2. Fill out the information for registration using a valid email
3. Click Register
4. Error happens here. Authentication Token error (something along those lines, I dont remember the exact error message)

**Expected behavior**
Member is emailed a password reset and is able to log into the website

**Screenshots**
Drag and drop images into the editor to include them.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 120

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tymorrow** [comment]
Hey @AbiAthmakuri034, I've published something that I hope fixes your issues.  Can you recheck things on your end and let me know how it goes?

**Comment by AbiAthmakuri034** [comment]
Hello @tymorrow, I have tried unregistering the members from the website to re-register them since I still get the "email is in use" error code. When I try to un-register them, It is followed with a sign in prompt and then an Error 500. Is there anyway they could be deleted from the database on your end?

**Comment by tymorrow** [comment]
Hi @AbiAthmakuri034, when you get a chance, try to unregister them again and let me know.

**Comment by AbiAthmakuri034** [comment]
I was able to register them from my end. I will keep you updated if they were able to sign in to the website. Thank you for your help @tymorrow!

**Comment by tymorrow** [comment]
Closing as resolved.  Feel free to open a new issue if it comes back up.
